### ISSUE TITLE
when patching ipsw without memory option will say no free space left on device

### ISSUE THREAD

**Issue by SmallPP420** [LukeZGD/iPhone4Down#11]
when i was trying to downgrade this device i didnt have enough memory for the memory option so i pressed N but after 2-3 minutes the ipsw patching failed saying there wasnt enough free space left so i decided to try on a external hard drive with 400gb free and still, no space left

**Comment by SmallPP420** [comment]
i was patching ios 5.1.1

**Comment by LukeZGD** [comment]
This is something that I cannot fix

The problem with ch3rryflower is that it uses `/tmp` when the memory option is disabled. However, `/tmp` is typically mounted as TMPFS in most Linux distros nowadays. This can be fixed by changing the tmp directory in the source code and recompiling it, however the version of ch3rryflower being used by iPhone4Down is not open-source. So your options are:

1. Get more RAM
2. Run `sudo umount /tmp; sudo rm /tmp; mkdir tmpfs; sudo ln -sf ./tmpfs /tmp` then run iPhone4Down again

**Comment by SmallPP420** [comment]
ill try this then

**Comment by SmallPP420** [comment]
sadly didnt work under a live usb environment :(

umount: /tmp: target is busy.
rm: cannot remove '/tmp': Device or resource busy

**Comment by LukeZGD** [comment]
> sadly didnt work under a live usb environment :(
> 
> umount: /tmp: target is busy. rm: cannot remove '/tmp': Device or resource busy

Try doing `sudo umount -lf /tmp` instead

**Comment by SmallPP420** [comment]
worked!

**Comment by SmallPP420** [comment]
now i have a weird seg fault


./restore.sh: line 394:  3041 Segmentation fault      (core dumped) $cherry/cherry $IPSW.ipsw $IPSWCustom.ipsw $JBMemory -derebusantiquis $IPSW7.ipsw iBoot ${JBFiles[@]}

**Comment by SmallPP420** [comment]
ok looks like im gonna risk it and do it in a non live env

**Comment by SmallPP420** [comment]
ended up breaking my os lol shouldve tooken ur warning into consideration but it was easy enough to fix

boot into live environment

launch terminal

cp -r /tmp path_to_broken_install/tmpfs && reboot
